# GENERATED FILE — do not edit.
# Source: tests/tests_async/conftest.py. Regenerate with `poetry run python unasync.py`.
"""Suite-local fixtures.

``tests/tests_sync/`` is generated by ``unasync.py``; edit the async sibling
directory, not the generated one.  Emulator plumbing (``firestore_client``,
``clean_collection``, ``require_emulator``) is inherited from
``tests/conftest.py``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING
from unittest.mock import Mock

import google.auth.credentials
import pytest
from firedantic.configurations import configuration

from tests.conftest import COLLECTION_PREFIX, EMULATOR_PROJECT

if TYPE_CHECKING:
    from google.cloud.firestore_v1.client import Client


@pytest.fixture
def configure_firedantic(firestore_client: Client) -> None:
    """Register firedantic configurations backed by the emulator.

    Function-scoped on purpose: ``configuration.add`` replaces the named config
    and drops any lazily-built client, so each test builds a fresh one.  That
    matters for the async flavour, where pytest-asyncio gives every test its
    own event loop and a gRPC channel must not outlive the loop it was created
    on.  Depends on ``firestore_client`` only for its ``FIRESTORE_EMULATOR_HOST``
    side effect.
    """
    # Default configuration
    configuration.add(
        name="(default)",
        prefix=COLLECTION_PREFIX,
        project=EMULATOR_PROJECT,
        credentials=Mock(spec=google.auth.credentials.Credentials),
    )

    # Backup configuration for testing multi-db routing
    configuration.add(
        name="backup",
        prefix=COLLECTION_PREFIX,
        project=EMULATOR_PROJECT,
        database="backup",
        credentials=Mock(spec=google.auth.credentials.Credentials),
    )
